@startuml

abstract class org.rudi.common.storage.entity.AbstractLabelizedEntity <<MappedSuperclass>>  {
	{field} {static} +CODE_COLUMN_LENGTH : int
	{field} {static} +CODE_COLUMN_NAME : String
	{field} +@Column("code") code : String
	{field} +@Column("label") label : String
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


abstract class org.rudi.common.storage.entity.AbstractLongIdEntity <<MappedSuperclass>>  {
	{field} +@Column("id") @Id id : Long
	{field} {static} -serialVersionUID : long
	{field} +@Column("uuid") uuid : java.util.UUID
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


abstract class org.rudi.common.storage.entity.AbstractLongIdEntity$AbstractLongIdEntityBuilder {
	{field} -id : Long
	{field} -uuid : java.util.UUID
	{method}  {abstract} +build () : org.rudi.common.storage.entity.AbstractLongIdEntity
	{method} +id ( id : Long ) : org.rudi.common.storage.entity.AbstractLongIdEntity$AbstractLongIdEntityBuilder
	{method}  {abstract} #self () : org.rudi.common.storage.entity.AbstractLongIdEntity$AbstractLongIdEntityBuilder
	{method} +toString () : String
	{method} +uuid ( uuid : java.util.UUID ) : org.rudi.common.storage.entity.AbstractLongIdEntity$AbstractLongIdEntityBuilder
}


abstract class org.rudi.common.storage.entity.AbstractStampedEntity <<MappedSuperclass>>  {
	{field} +@Column("closing_date") closingDate : java.time.LocalDateTime
	{field} +@Column("opening_date") openingDate : java.time.LocalDateTime
	{field} +@Column("order_") order : int
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


abstract class org.rudi.common.storage.entity.AbstractTranslationEntity <<MappedSuperclass>>  {
	{field} +@Column("lang") lang : String
	{field} {static} -serialVersionUID : long
	{field} +@Column("text") text : String
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.common.storage.entity.HibernateEntityHelper {
	{method}  {static} +setCollection ( collectionGetter : java.util.function.Supplier , newCollection : java.util.Collection ) : void
}


interface org.rudi.common.storage.entity.PositionedStatus {
	{method}  {abstract} +isFinal () : boolean
	{method}  {abstract} +isInitial () : boolean
}


class org.rudi.common.storage.entity.SkosConceptCodeColumn {
	{field} {static} +LENGTH : int
	{field} {static} +NAME : String
	{field} {static} +TABLE_NAME : String
}


enum org.rudi.common.storage.entity.StatusPosition {
	{field} +FINAL
	{field} +INITIAL
	{field} +INTERMEDIATE
}


class org.rudi.facet.bpmn.entity.form.FormDefinitionEntity <<Entity>>  <<Table>>  {
 {TableName=form_definition}
--
	{field} +@Column("name") name : String
	{field} {static} -serialVersionUID : long
	{method} +addFormSectionDefinition ( formSectionDefinitionEntity : org.rudi.facet.bpmn.entity.form.FormSectionDefinitionEntity ) : void
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +lookupFormSectionDefinition ( uuid : java.util.UUID ) : org.rudi.facet.bpmn.entity.form.FormSectionDefinitionEntity
	{method} +toString () : String
}


class org.rudi.facet.bpmn.entity.form.FormSectionDefinitionEntity <<Entity>>  <<Table>>  {
 {TableName=form_section_definition}
--
	{field} +@Column("order_") order : int
	{field} +@Column("read_only") readOnly : boolean
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.facet.bpmn.entity.form.ProcessFormDefinitionEntity <<Entity>>  <<Table>>  {
 {TableName=process_form_definition}
--
	{field} +@Column("action_name") actionName : String
	{field} +@Column("process_definition_id") processDefinitionId : String
	{field} +@Column("revision") revision : Integer
	{field} {static} -serialVersionUID : long
	{field} +@Column("user_task_id") userTaskId : String
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.facet.bpmn.entity.form.SectionDefinitionEntity <<Entity>>  <<Table>>  {
 {TableName=section_definition}
--
	{field} +@Column("definition") definition : String
	{field} +@Column("help") help : String
	{field} +@Column("label") label : String
	{field} +@Column("name") name : String
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


abstract class org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity <<MappedSuperclass>>  {
	{field} +@Column("assignee") assignee : String
	{field} +@Column("creation_date") creationDate : java.time.LocalDateTime
	{field} +@Column("data") data : String
	{field} +@Column("description") description : String
	{field} +@Column("functional_status") functionalStatus : String
	{field} +@Column("initiator") initiator : String
	{field} +@Column("process_definition_key") processDefinitionKey : String
	{field} +@Column("process_definition_version") processDefinitionVersion : Integer
	{field} {static} -serialVersionUID : long
	{field} +@Column("status") status : org.rudi.bpmn.core.bean.Status
	{field} +@Column("updated_date") updatedDate : java.time.LocalDateTime
	{field} +@Column("updator") updator : String
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


abstract class org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder {
	{field} -assignee : String
	{field} -creationDate : java.time.LocalDateTime
	{field} -data : String
	{field} -description : String
	{field} -functionalStatus : String
	{field} -initiator : String
	{field} -processDefinitionKey : String
	{field} -processDefinitionVersion : Integer
	{field} -status : org.rudi.bpmn.core.bean.Status
	{field} -updatedDate : java.time.LocalDateTime
	{field} -updator : String
	{method} +assignee ( assignee : String ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method}  {abstract} +build () : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity
	{method} +creationDate ( creationDate : java.time.LocalDateTime ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +data ( data : String ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +description ( description : String ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +functionalStatus ( functionalStatus : String ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +initiator ( initiator : String ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +processDefinitionKey ( processDefinitionKey : String ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +processDefinitionVersion ( processDefinitionVersion : Integer ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method}  {abstract} #self () : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +status ( status : org.rudi.bpmn.core.bean.Status ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +toString () : String
	{method} +updatedDate ( updatedDate : java.time.LocalDateTime ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
	{method} +updator ( updator : String ) : org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder
}


interface org.rudi.facet.bpmn.entity.workflow.AssetDescriptionEntity {
	{method}  {abstract} +getAssignee () : String
	{method}  {abstract} +getCreationDate () : java.time.LocalDateTime
	{method}  {abstract} +getData () : String
	{method}  {abstract} +getDescription () : String
	{method}  {abstract} +getFunctionalStatus () : String
	{method}  {abstract} +getInitiator () : String
	{method}  {abstract} +getProcessDefinitionKey () : String
	{method}  {abstract} +getProcessDefinitionVersion () : Integer
	{method}  {abstract} +getStatus () : org.rudi.bpmn.core.bean.Status
	{method}  {abstract} +getUpdatedDate () : java.time.LocalDateTime
	{method}  {abstract} +getUpdator () : String
	{method}  {abstract} +setAssignee ( assignee : String ) : void
	{method}  {abstract} +setCreationDate ( creationDate : java.time.LocalDateTime ) : void
	{method}  {abstract} +setData ( data : String ) : void
	{method}  {abstract} +setDescription ( description : String ) : void
	{method}  {abstract} +setFunctionalStatus ( functionalStatus : String ) : void
	{method}  {abstract} +setInitiator ( initiator : String ) : void
	{method}  {abstract} +setProcessDefinitionKey ( businessKey : String ) : void
	{method}  {abstract} +setProcessDefinitionVersion ( version : Integer ) : void
	{method}  {abstract} +setStatus ( status : org.rudi.bpmn.core.bean.Status ) : void
	{method}  {abstract} +setUpdatedDate ( updatedDate : java.time.LocalDateTime ) : void
	{method}  {abstract} +setUpdator ( updator : String ) : void
}


class org.rudi.facet.doks.entity.DocumentEntity <<Entity>>  <<Table>>  {
 {TableName=document}
--
	{field} +@Column("") contentType : String
	{field} +@Column("") encrypted : boolean
	{field} +@Column("") fileContents : java.sql.Blob
	{field} +@Column("") fileName : String
	{field} +@Column("") fileSize : long
	{field} {static} -serialVersionUID : long
	{field} +@Column("") uploaderUuid : java.util.UUID
	{method}  {static} -$default$encrypted () : boolean
	{method}  {static} +builder () : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
	{method} +equals ( o : Object ) : boolean
	{method} +hashCode () : int
	{method} +toBuilder () : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
	{method} +toString () : String
}


class org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder {
	{field} -contentType : String
	{field} -encrypted$set : boolean
	{field} -encrypted$value : boolean
	{field} -fileContents : java.sql.Blob
	{field} -fileName : String
	{field} -fileSize : long
	{field} -uploaderUuid : java.util.UUID
	{method} +build () : org.rudi.facet.doks.entity.DocumentEntity
	{method} +contentType ( contentType : String ) : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
	{method} +encrypted ( encrypted : boolean ) : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
	{method} +fileContents ( fileContents : java.sql.Blob ) : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
	{method} +fileName ( fileName : String ) : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
	{method} +fileSize ( fileSize : long ) : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
	{method} +toString () : String
	{method} +uploaderUuid ( uploaderUuid : java.util.UUID ) : org.rudi.facet.doks.entity.DocumentEntity$DocumentEntityBuilder
}


abstract class org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity <<Entity>>  <<Table>>  {
 {TableName=abstract_address}
 {TableSchema=strukture_data}
--
	{field} {static} -serialVersionUID : long
	{method} +equals ( o : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.microservice.strukture.storage.entity.address.AddressRoleEntity <<Entity>>  <<Table>>  {
 {TableName=address_role}
 {TableSchema=strukture_data}
--
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


enum org.rudi.microservice.strukture.storage.entity.address.AddressType {
	{field} +EMAIL
	{field} +PHONE
	{field} +POSTAL
	{field} +WEBSITE
}


class org.rudi.microservice.strukture.storage.entity.address.EmailAddressEntity <<Entity>>  <<Table>>  {
 {TableName=email_address}
 {TableSchema=strukture_data}
--
	{field} +@Column("email") email : String
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.microservice.strukture.storage.entity.address.PostalAddressEntity <<Entity>>  <<Table>>  {
 {TableName=postal_address}
 {TableSchema=strukture_data}
--
	{field} +@Column("additionalIdentification") additionalIdentification : String
	{field} +@Column("distributionService") distributionService : String
	{field} +@Column("locality") locality : String
	{field} +@Column("recipientIdentification") recipientIdentification : String
	{field} {static} -serialVersionUID : long
	{field} +@Column("streetNumber") streetNumber : String
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.microservice.strukture.storage.entity.address.TelephoneAddressEntity <<Entity>>  <<Table>>  {
 {TableName=telephone_address}
 {TableSchema=strukture_data}
--
	{field} +@Column("phone_number") phoneNumber : String
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.microservice.strukture.storage.entity.address.WebsiteAddressEntity <<Entity>>  <<Table>>  {
 {TableName=web_site_address}
 {TableSchema=strukture_data}
--
	{field} {static} -serialVersionUID : long
	{field} +@Column("url") url : String
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.microservice.strukture.storage.entity.organization.OrganizationEntity <<Entity>>  <<Table>>  {
 {TableName=organization}
 {TableSchema=strukture_data}
--
	{field} {static} +FIELD_MEMBERS : String
	{field} {static} +FIELD_ORGANIZATION_STATUS : String
	{field} {static} +FIELD_UUID : String
	{field} +@Column("address") address : String
	{field} +closingDate : java.time.LocalDateTime
	{field} +name : String
	{field} +openingDate : java.time.LocalDateTime
	{field} +@Column("position") position : org.locationtech.jts.geom.Geometry
	{field} {static} -serialVersionUID : long
	{field} +@Column("url") url : String
	{method} +equals ( o : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.microservice.strukture.storage.entity.organization.OrganizationMemberEntity {
	{field} {static} +FIELD_ID : String
	{field} {static} +FIELD_ROLE : String
	{field} {static} +FIELD_USER_UUID : String
	{field} +addedDate : java.time.LocalDateTime
	{field} {static} -serialVersionUID : long
	{field} +userUuid : java.util.UUID
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


enum org.rudi.microservice.strukture.storage.entity.organization.OrganizationRole {
	{field} +ADMINISTRATOR
	{field} +EDITOR
}


enum org.rudi.microservice.strukture.storage.entity.organization.OrganizationStatus {
	{field} +CANCELLED
	{field} +DISENGAGED
	{field} +DRAFT
	{field} +IN_PROGRESS
	{field} +VALIDATED
}


class org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerEntity <<Entity>>  <<Table>>  {
 {TableName=linked_producer}
 {TableSchema=strukture_data}
 {TableUniqueConstraints=UniqueConstraint (columnNames=[organization_fk,provider_fk] )}
--
	{field} {static} +FIELD_ID : String
	{field} {static} +FIELD_ORGANIZATION : String
	{field} {static} +FIELD_UUID : String
	{field} {static} +ORGANIZATION_FK : String
	{field} {static} +PROVIDER_FK : String
	{method} +equals ( o : Object ) : boolean
	{method} +hashCode () : int
}


enum org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerStatus {
	{field} +CANCELLED
	{field} +DISENGAGED
	{field} +DRAFT
	{field} +IN_PROGRESS
	{field} +VALIDATED
}


class org.rudi.microservice.strukture.storage.entity.provider.NodeProviderEntity <<Entity>>  <<Table>>  {
 {TableName=node_provider}
 {TableSchema=strukture_data}
--
	{field} +@Column("closing_date") closingDate : java.time.LocalDateTime
	{field} +@Column("harvestable") harvestable : boolean
	{field} +@Column("harvesting_cron") harvestingCron : String
	{field} +@Column("last_harvesting_date") lastHarvestingDate : java.time.LocalDateTime
	{field} +@Column("notifiable") notifiable : boolean
	{field} +@Column("opening_date") openingDate : java.time.LocalDateTime
	{field} {static} -serialVersionUID : long
	{field} +@Column("url") url : String
	{field} +@Column("version") version : String
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class org.rudi.microservice.strukture.storage.entity.provider.ProviderEntity <<Entity>>  <<Table>>  {
 {TableName=provider}
 {TableSchema=strukture_data}
--
	{field} {static} +FIELD_ID : String
	{field} {static} +FIELD_LINKED_PRODUCERS : String
	{field} {static} +FIELD_UUID : String
	{field} {static} -serialVersionUID : long
	{method} +equals ( obj : Object ) : boolean
	{method} +hashCode () : int
	{method} +lookupAddress ( uuid : java.util.UUID ) : org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity
	{method} +lookupNodeProvider ( uuid : java.util.UUID ) : org.rudi.microservice.strukture.storage.entity.provider.NodeProviderEntity
	{method} +removeAddress ( uuid : java.util.UUID ) : org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity
	{method} +removeNodeProvider ( uuid : java.util.UUID ) : org.rudi.microservice.strukture.storage.entity.provider.NodeProviderEntity
	{method} +toString () : String
}




org.rudi.common.storage.entity.AbstractLabelizedEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.common.storage.entity.AbstractStampedEntity --|>  org.rudi.common.storage.entity.AbstractLabelizedEntity
org.rudi.common.storage.entity.AbstractTranslationEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.facet.bpmn.entity.form.FormDefinitionEntity "1" o-- "0..*"  org.rudi.facet.bpmn.entity.form.FormSectionDefinitionEntity :  @OneToMany\nformSectionDefinitions
org.rudi.facet.bpmn.entity.form.FormDefinitionEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.facet.bpmn.entity.form.FormSectionDefinitionEntity -->  org.rudi.facet.bpmn.entity.form.SectionDefinitionEntity :  @ManyToOne\nsectionDefinition
org.rudi.facet.bpmn.entity.form.FormSectionDefinitionEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.facet.bpmn.entity.form.ProcessFormDefinitionEntity -->  org.rudi.facet.bpmn.entity.form.FormDefinitionEntity :  @ManyToOne\nformDefinition
org.rudi.facet.bpmn.entity.form.ProcessFormDefinitionEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.facet.bpmn.entity.form.SectionDefinitionEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity ..|>  org.rudi.facet.bpmn.entity.workflow.AssetDescriptionEntity
org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity$AbstractAssetDescriptionEntityBuilder --|>  org.rudi.common.storage.entity.AbstractLongIdEntity$AbstractLongIdEntityBuilder
org.rudi.facet.doks.entity.DocumentEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity -->  org.rudi.microservice.strukture.storage.entity.address.AddressRoleEntity :  @ManyToOne\naddressRole
org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity -->  org.rudi.microservice.strukture.storage.entity.address.AddressType :  @Column("type")\ntype
org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.microservice.strukture.storage.entity.address.AddressRoleEntity -->  org.rudi.microservice.strukture.storage.entity.address.AddressType :  @Column("type")\ntype
org.rudi.microservice.strukture.storage.entity.address.AddressRoleEntity --|>  org.rudi.common.storage.entity.AbstractStampedEntity
org.rudi.microservice.strukture.storage.entity.address.EmailAddressEntity --|>  org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity
org.rudi.microservice.strukture.storage.entity.address.PostalAddressEntity --|>  org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity
org.rudi.microservice.strukture.storage.entity.address.TelephoneAddressEntity --|>  org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity
org.rudi.microservice.strukture.storage.entity.address.WebsiteAddressEntity --|>  org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity
org.rudi.microservice.strukture.storage.entity.organization.OrganizationEntity "1" o-- "0..*"  org.rudi.microservice.strukture.storage.entity.organization.OrganizationMemberEntity : members
org.rudi.microservice.strukture.storage.entity.organization.OrganizationEntity -->  org.rudi.microservice.strukture.storage.entity.organization.OrganizationStatus :  @Column("organization_status")\norganizationStatus
org.rudi.microservice.strukture.storage.entity.organization.OrganizationEntity --|>  org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity
org.rudi.microservice.strukture.storage.entity.organization.OrganizationMemberEntity -->  org.rudi.microservice.strukture.storage.entity.organization.OrganizationRole : role
org.rudi.microservice.strukture.storage.entity.organization.OrganizationStatus ..|>  org.rudi.common.storage.entity.PositionedStatus
org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerEntity -->  org.rudi.microservice.strukture.storage.entity.organization.OrganizationEntity :  @ManyToOne\norganization
org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerEntity -->  org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerStatus :  @Column("linked_producer_status")\nlinkedProducerStatus
org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerEntity --|>  org.rudi.facet.bpmn.entity.workflow.AbstractAssetDescriptionEntity
org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerStatus ..|>  org.rudi.common.storage.entity.PositionedStatus
org.rudi.microservice.strukture.storage.entity.provider.NodeProviderEntity --|>  org.rudi.common.storage.entity.AbstractLongIdEntity
org.rudi.microservice.strukture.storage.entity.provider.ProviderEntity "1" o-- "0..*"  org.rudi.microservice.strukture.storage.entity.address.AbstractAddressEntity :  @OneToMany\naddresses
org.rudi.microservice.strukture.storage.entity.provider.ProviderEntity "1" o-- "0..*"  org.rudi.microservice.strukture.storage.entity.provider.LinkedProducerEntity :  @OneToMany\nlinkedProducers
org.rudi.microservice.strukture.storage.entity.provider.ProviderEntity "1" o-- "0..*"  org.rudi.microservice.strukture.storage.entity.provider.NodeProviderEntity :  @OneToMany\nnodeProviders
org.rudi.microservice.strukture.storage.entity.provider.ProviderEntity --|>  org.rudi.common.storage.entity.AbstractStampedEntity

hide methods

@enduml