CREATE TABLE if NOT EXISTS projekt_data.related_organization
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    uuid              uuid NOT NULL UNIQUE,
    organization_uuid uuid,
    relation_status   varchar(50),
    project_fk        bigint,
    PRIMARY KEY (id)
);

ALTER TABLE if EXISTS projekt_data.related_organization ADD CONSTRAINT FK8pyw751m7inhihkrmtrk0hebk FOREIGN KEY (project_fk) REFERENCES projekt_data.project;